#!/usr/bin/env python
import csv

# Define the name of the input and output files
input_file = 'cache.csv'
output_file = 'phdeis'

# Open the input file and read in the data
with open(input_file, newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    data = list(reader)

# Sort the data by date_accessed in descending order
data_sorted = sorted(data, key=lambda x: x['date_accessed'], reverse=True)

# Define the HTML template for each item in the list
item_template = '<li><a href="{link}"><strong>{title}</strong></a> ({year})<br>by {authors}<br>Fetched: {date_accessed}</li>'

# Generate the HTML code for the list of items
items_html = '\n'.join([item_template.format(**item) for item in data_sorted])

# Define the HTML template for the whole page
page_template = '<html><head><title>List of papers</title></head><body><ul style="font-family: monospace;">{items_html}</ul></body></html>'

# Fill in the template with the list of items
page_html = page_template.format(items_html=items_html)

# Write the generated HTML code to the output file
with open(output_file, 'w', encoding='utf-8') as outfile:
    outfile.write(page_html)
